# Generated by Django 3.0.7 on 2020-06-28 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_favorites'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorites',
            old_name='tweet_id',
            new_name='tweet',
        ),
        migrations.RenameField(
            model_name='favorites',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='tweet',
            old_name='user_id',
            new_name='user',
        ),
    ]
